spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: telemetry-aggregator
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual

telemetry:
  aggregation:
    cleanup-interval: 30s
    windows:
      - name: "1m"
        duration: 1m
        retention: 10m
      - name: "5m"
        duration: 5m
        retention: 2h
      - name: "30m"
        duration: 30m
        retention: 2h
      - name: "1h"
        duration: 1h
        retention: 10h
      - name: "6h"
        duration: 6h
        retention: 10h

  kafka:
    topics:
      - telemetry-all
      - telemetry-success
      - telemetry-error